### ISSUE TITLE
`http3` package versions `0.0.16` and `0.0.17` don't build with `http-semantics-0.2.1`

### ISSUE THREAD

**Issue by Vlix** [kazu-yamamoto/http3#6]
The cabal dependency constraints for `http3-0.0.16` and `http3-0.0.17` should probably be updated to
```cabal
build-depends:
    ...
    http-semantics == 0.2.0,
    ...
```
Since they fail with the following error on `http-semantics-0.2.1` or higher:
```hs
http3 > /tmp/stack-f40acd5b3bc8b507/http3-0.0.16/Network/HTTP3/Send.hs:113:17: error: [GHC-95909]
http3 >     • Constructor ‘OutBodyIface’ does not have the required strict field(s):
http3 >         outBodyCancel :: Maybe E.SomeException -> IO ()
http3 >     • In the expression:
http3 >         OutBodyIface
http3 >           {outBodyUnmask = unmask, outBodyPush = write ref,
http3 >            outBodyPushFinal = write ref, outBodyFlush = flush}
http3 >       In an equation for ‘iface’:
http3 >           iface
http3 >             = OutBodyIface
http3 >                 {outBodyUnmask = unmask, outBodyPush = write ref,
http3 >                  outBodyPushFinal = write ref, outBodyFlush = flush}
http3 >       In the expression:
http3 >         do let iface = ...
http3 >            strmbdy iface
http3 >     |
http3 > 113 |                 OutBodyIface
http3 >     |                 ^^^^^^^^^^^^...
```

**Comment by kazu-yamamoto** [comment]
This is my bad.
Sorry for your inconvenience.
I have updated the metadata on Hackage.
